apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow-k8s

spec:
  type: LoadBalancer
  selector:
    app: airflow-webserver
  
  ports:
  - port: 8080
    targetPort: 8080
